name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-and-precommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pre-commit
        run: |
          source .venv/bin/activate
          pre-commit run --all-files
